site_name: 你所描绘的魔法世界
nav:
  - 序: index.md
  - 随笔:
    # - 11. 知行记: 随笔/知行记.md
    - 16. 最终的行动: 随笔/最终的行动.md
    - 15. 总结: 随笔/总结.md
    - 14. 时间: 随笔/时间.md
    - 13. 走出政治: 随笔/走出政治.md
    - 12. 文学生死间: 随笔/文学生死间.md
    - 11. 遥看春雪: 随笔/遥看春雪.md
    - 10. 十二月杂书: 随笔/轨迹03.md
    - 09. 十一月六日夜: 随笔/轨迹02.md
    - 08. 8月杂书: 随笔/轨迹01.md
    - 07. 日出，夜晚，旋转的世界与海洋: 随笔/海洋.md
    - 06. 再读滕洋: 随笔/再读滕洋.md
    - 05. 诚实的责任: 随笔/诚实的责任.md
    - 04. 美的重量: 随笔/美的重量.md
    - 03. 无边际的战场: 随笔/无边际的战场.md
    - 02. 佛教浅读: 随笔/佛教浅读.md
    - 01. 本命年: 随笔/本命年.md
  - 摘录集:
    - 分类摘录:
      - 01. 静态实体:
        - 1.1 自然, 环境, 氛围: 摘录集/分类摘录/01_静态实体/1.1_自然_环境_氛围.md
        - 1.2 肉体, 肖像: 摘录集/分类摘录/01_静态实体/1.2_肉体_肖像.md
        - 1.3 器物, 静物: 摘录集/分类摘录/01_静态实体/1.3_器物_静物.md
      - 02. 因果动态:
        - 2.1 动作, 行为: 摘录集/分类摘录/02_因果动态/2.1_动作_行为.md
        - 2.2 互动, 对话: 摘录集/分类摘录/02_因果动态/2.2_互动_对话.md
        - 2.2 转场, 衔接: 摘录集/分类摘录/02_因果动态/2.2_转场_衔接.md
      - 03. 抽象精神:
        - 3.1 心理活动, 潜意识: 摘录集/分类摘录/03_抽象精神/3.1_心理活动_潜意识.md
        - 3.2 洞见, 总结: 摘录集/分类摘录/03_抽象精神/3.2_洞见_总结.md
        - 3.3 情感, 心境: 摘录集/分类摘录/03_抽象精神/3.3_情感_心境.md
    - 03. 摘录集-有无之境 (陈来): 摘录集/摘录集-有无之境.md
    - 02. 摘录集-论语 (孔子): 摘录集/摘录集-论语.md
    - 01. 摘录集-春雪 (三岛由纪夫): 摘录集/摘录集-春雪.md
    # - Garnet Crow:
    # - 01. 夏の幻: 01_夏の幻.md

      #   - 摘录集:
      #     - A1. 再见！彼得潘 · 滕洋: A1_goodbyePeterPan.md
      #     - A2. 雨中的喷泉 · 三岛由纪夫: A2_FountainInRain.md

theme:
  name: material



